Areas/Student/Controllers/MST_StudentController.cs
using AdminPanel_New.Areas.States.Models;
using AdminPanel_New.Areas.Student.Models;
using AdminPanel_New.DAL.MST_StudentDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_New.Areas.Student.Controllers
{
    [Area("Student")]
    [Route("Student/[controller]/[action]")]
    public class MST_StudentController : Controller
    {
        MST_StudentDAL mst_StudentDAL=new MST_StudentDAL();

        #region MST_StudentList
        public IActionResult MST_StudentList()
        {
            DataTable dt = mst_StudentDAL.PR_Student_SelectAll();
            return View(dt);
        }
        #endregion

        #region Add
        public IActionResult Add(int ?StudentID)
        {
            if (StudentID == null)
            {
                ViewBag.BranchList = mst_StudentDAL.PR_Branch_ComboBox();
                ViewBag.CityList = mst_StudentDAL.PR_LOC_City_SelectComboBox();
                return View("AddEditStudent");
            }
            else
            {
                ViewBag.BranchList = mst_StudentDAL.PR_Branch_ComboBox();
                ViewBag.CityList = mst_StudentDAL.PR_LOC_City_SelectComboBox();
                MST_StudentModel model=mst_StudentDAL.PR_Student_SelectByPk(StudentID);
                return View("AddEditStudent",model);
            }
        }

        #endregion

        #region AddEditStudent
        public IActionResult AddEditStudent(MST_StudentModel model)
        {
            if (mst_StudentDAL.Save(model))
            {
                return RedirectToAction("MST_StudentList");
            }

            return View();
        }

        #endregion

        #region Delete
        public IActionResult Delete(int StudentID)
        {
            mst_StudentDAL.PR_Student_DeleteByPK(StudentID);
            return RedirectToAction("MST_StudentList");  
        }
        #endregion
    }
}

Areas/Student/Views/MST_Student/AddEditStudent.cshtml
﻿﻿@{
    Layout = "~/Views/shared/_Layout.cshtml";
}

@model AdminPanel_New.Areas.Student.Models.MST_StudentModel;
<div class="d-flex flex-column">
    <form method="post">
        @Html.HiddenFor(x=>x.StudentID)
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="mt-3 mb-3">
            <h2>Add / Update Page</h2>
        </div>
        <div class="mb-3 row form-group">
            <label class="col-sm-2 col-form-label">Student Name</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="StudentName" />
                <span asp-validation-for="StudentName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group mb-3 row">
            <label class="col-sm-2 control-label col-form-label">Branch</label>
            <div class="col-xl-4">
                <select class="form-control" asp-for="BranchID" asp-items="@(new SelectList(ViewBag.BranchList,"BranchID","BranchName"))">
                    <option value="">Select Branch</option>
                </select>
                <span asp-validation-for="BranchID" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group mb-3 row">
            <label class="col-sm-2 control-label col-form-label">City</label>
            <div class="col-xl-4">
                <select class="form-control" asp-for="CityID" asp-items="@(new SelectList(ViewBag.CityList,"CityID","CityName"))">
                    <option value="">Select City</option>
                </select>
                <span asp-validation-for="CityID" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Mobile No Father</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="MobileNoFather" />
                <span asp-validation-for="MobileNoFather" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Mobile No Student</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="MobileNoStudent" />
                <span asp-validation-for="MobileNoStudent" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Email</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="Email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Address</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="Address" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">BirthDate</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="BirthDate" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Age</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="Age" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">IsActive</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="IsActive" />
                <span asp-validation-for="IsActive" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Gender</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="Gender" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
        </div>
        <div class="mb-3 row">
            <label class="col-sm-2 col-form-label">Password</label>
            <div class="col-xl-4">
                <input type="text" class="form-control" asp-for="Password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-success" type="submit" asp-area="Student" asp-controller="MST_Student" asp-action="AddEditStudent">Save</button>
        </div>
    </form>
</div>

Areas/Student/Views/MST_Student/MST_StudentList.cshtml
@using System.Data;
@using AdminPanel_New.Areas.Student.Models;
@model DataTable
@{
    ViewData["Title"] = "Student List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<form class="row row-cols-lg-auto g-3 align-items-center">
    <h1 class="text-center">Student List</h1>
    <div class="text-center">
        <input type="submit" class="btn btn-primary m-4 " value="ADD Student" asp-action="Add" asp-controller="MST_Student" asp-area="Student">
    </div>
</form>

<br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">StudentName</th>
            <th scope="col">BranchName</th>
            <th scope="col">CityName</th>
            <th scope="col">Gender</th>
            <th scope="col">Email</th>
            <th scope="col">Age</th>
            <th scope="col">Actions</th>



        </tr>
    </thead>
    <tbody>
        @foreach (DataRow dr in Model.Rows)
        {
            <tr>
                <td>@dr["StudentName"]</td>
                <td>@dr["BranchName"]</td>
                <td>@dr["CityName"]</td>
                <td>@dr["Gender"]</td>
                <td>@dr["Email"]</td>
                <td>@dr["Age"]</td>
                @* <td>@Convert.ToDateTime(dr["BirthDate"]).ToString("MM/dd/yyyy H:mm")</td> *@
           @*      <td>@dr["MobileNoStudent"]</td>
                <td>@dr["MobileNoFather"]</td> *@
         @*        <td>@Convert.ToDateTime(dr["Created"]).ToString("MM/dd/yyyy H:mm")</td>
                <td>@Convert.ToDateTime(dr["Modified"]).ToString("MM/dd/yyyy H:mm")</td> *@
                <td>
                    <form asp-area="Student" asp-controller="MST_Student" asp-action="Delete">
                        <input type="hidden" name="StudentID" value="@Convert.ToInt32(dr["StudentID"])">
                        <button type="submit" class="btn btn-danger btn-xs">delete</button>
                        <a class="btn btn-info btn-xs" asp-area="Student" asp-controller="MST_Student" asp-action="Add" asp-route-studentid="@Convert.ToInt32(dr["StudentID"])">edit</a>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>
        