Areas/Branch/Controllers/MST_BranchController.cs
using AdminPanel_New.Areas.Branch.Models;
using AdminPanel_New.DAL.MST_BranchDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_New.Areas.Branch.Controllers
{
    [Area("Branch")]
    [Route("Branch/[controller]/[action]")]
    public class MST_BranchController : Controller
    {
        MST_BranchDAL mst_BranchDAl=new MST_BranchDAL();

        #region BranchList
        public IActionResult MST_BranchList()
        {
            DataTable dt=mst_BranchDAl.PR_Branch_SelectAll();
            return View(dt);
        }

        #endregion

        #region Add NAvigator For Render PAge
        public IActionResult Add(int ? BranchID)
        {
            if(BranchID != null)
            {
                MST_BranchModel model = mst_BranchDAl.PR_Branch_SelectByPk(BranchID);
                return View("AddEditBranch",model);
            }
            else
            {
                return View("AddEditBranch");
            }

        }
        #endregion

        #region AddEditBranch
        public IActionResult AddEditBranch(MST_BranchModel model)
        {
            if (mst_BranchDAl.SaveBranch(model))
            {
                return RedirectToAction("MST_BranchList");
            }
            else
            {
                return View();
            }
            
        }
        #endregion

        #region Delete
        public IActionResult Delete(int ?BranchID)
        {
            Console.WriteLine(BranchID);

                mst_BranchDAl.PR_Branch_DeleteByPK(BranchID);
                return RedirectToAction("MST_BranchList");
        }
        #endregion
    }
}

Areas/City/Controllers/LOC_CityController.cs
using AdminPanel_New.DAL.LOC_CityDAL;
using AdminPanel_New.DAL.LOC_StateDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using AdminPanel_New.Areas.City.Models;

namespace AdminPanel_New.Areas.City.Controllers
{
    [Area("City")]
    [Route("City/[controller]/[action]")]
    public class LOC_CityController : Controller
    {
       
        LOC_CityDAL dalLOC_CityDAL= new LOC_CityDAL();
        LOC_StateDAL dalLOC_StateDAL = new LOC_StateDAL();

        #region LOC_CityList Controller
        public IActionResult LOC_CityList()
        {
            DataTable dt = dalLOC_CityDAL.dbo_PR_LOC_City_SelectAll();
            return View(dt);
        }
        #endregion

        #region ADD Method 
        public IActionResult Add(int ?CityID)
        {
            if (CityID == null)
            {
                ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
                ViewBag.StateList = dalLOC_CityDAL.DropDownState();
                return View("AddEditCity");
            }
            else
            {
                LOC_CityModel model= dalLOC_CityDAL.PR_LOC_City_SelectByPK(CityID);
                ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
                ViewBag.StateList = dalLOC_CityDAL.PR_LOC_State_SelectComboBoxByCountryID(model.CountryID);
                return View("AddEditCity",model);
            }
        }
        #endregion

        #region AddEditCity
        public IActionResult AddEditCity(LOC_CityModel model)
        {
            if (dalLOC_CityDAL.SaveCity(model))
            {
                return RedirectToAction("LOC_CityList");
            }
            return View("AddEditCity");
            
        }
        #endregion

        #region Delete
        public IActionResult Delete(int? CityID)
        {
            dalLOC_CityDAL.PR_LOC_City_Delete(CityID);
            return RedirectToAction("LOC_CityList");
        }
        #endregion

        #region DropDownByCountryForState
        public IActionResult DropDownByCountryForState(int CountryID)
        {
            var model=dalLOC_CityDAL.PR_LOC_State_SelectComboBoxByCountryID(CountryID);
            return Json(model);
        }

        #endregion

        #region SearchCity
        public IActionResult SearchCity(string CityName)
        {
            DataTable dt=dalLOC_CityDAL.PR_City_SelectByCityName(CityName);
            return View("LOC_CityList",dt);
        }
        #endregion
    }
}

Areas/Country/Controllers/LOC_CountryController.cs
using AdminPanel_New.Areas.Country.Models;
using AdminPanel_New.DAL.LOC_CountryDAL;
using AdminPanel_New.DAL.LOC_StateDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_New.Areas.Country.Controllers
{
    [Area("Country")]
    [Route("Country/[controller]/[action]")]
    public class LOC_CountryController : Controller
    {
        LOC_CountryModel modelLOC_Country = new LOC_CountryModel();
        LOC_CountryDAL dalLOC_CountryDAL = new LOC_CountryDAL();

        #region LOC_CountryList Controller
        public IActionResult LOC_CountryList()
        {
            DataTable dt = dalLOC_CountryDAL.dbo_PR_LOC_Country_SelectAll();
            return View(dt);
        }
        #endregion

        #region Add NAvigator For Render PAge
        public IActionResult Add(int? CountryID)
        {


            LOC_CountryModel model = dalLOC_CountryDAL.PR_LOC_Country_SelectByPK(CountryID);
            if (model != null)
            {
                return View("AddEditCountry", model);
            }
            else
            {
                return View("AddEditCountry");
            }
        }
        #endregion

        #region Add /Edit Page Controller
        public IActionResult AddEditCountry(LOC_CountryModel modelLOC_CountryModel)
        {
            if (ModelState.IsValid)
            {
                if (dalLOC_CountryDAL.SaveCountry(modelLOC_CountryModel))
                {
                    if (modelLOC_CountryModel.CountryID == null)
                    {
                        TempData["CountryInsertMsg"] = "Record Inserted Successfully";
                        return RedirectToAction("LOC_CountryList");
                    }
                    else
                        return RedirectToAction("LOC_CountryList");
                }
            }
            return View("AddEditCountry");
        }
        #endregion

        #region Delete 
        public IActionResult Delete(int? CountryID)
        {
            dalLOC_CountryDAL.PR_LOC_deleteCity_FollowedBy_Country(CountryID);
            dalLOC_CountryDAL.PR_LOC_deleteState_FollowedBy_Country(CountryID);
            dalLOC_CountryDAL.PR_LOC_Country_Delete(CountryID);
            return RedirectToAction("LOC_CountryList");
        }
        #endregion

        #region SearchContry
        public IActionResult SearchContry(string CountryName)
        {
            DataTable dt = dalLOC_CountryDAL.PR_Country_SelectByCountryName(CountryName);
            return View("LOC_CountryList",dt);
        }
        #endregion
    }
}

Areas/States/Controllers/LOC_StateController.cs
using AdminPanel_New.Areas.States.Models;
using AdminPanel_New.DAL.LOC_StateDAL;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace AdminPanel_New.Areas.States.Controllers
{
    [Area("States")]
    [Route("States/[controller]/[action]")]
    public class LOC_StateController : Controller
    {
        LOC_StateDAL dalLOC_StateDAL = new LOC_StateDAL();
        #region LOC_StateList
        public IActionResult LOC_StateList()
        {
            List<LOC_StateModel> models = new List<LOC_StateModel>();
            DataTable dt = dalLOC_StateDAL.dbo_PR_LOC_State_SelectAll();
            foreach(DataRow dr in dt.Rows)
            {

            }
            ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
            return View(dt);
        }
        #endregion

        #region ADD
        public IActionResult Add(int ? StateID)
        {
            if(StateID == null)
            {
                ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
                return View("AddEditState");
            }
            else
            {
                LOC_StateModel model= dalLOC_StateDAL.PR_LOC_State_SelectByPK(StateID);
                ViewBag.CountryList = dalLOC_StateDAL.DropdownCountry();
                return View("AddEditState",model);
            }

        }
        #endregion

        #region ADD & Edit State
        public IActionResult AddEditState(LOC_StateModel model)
        {
            LOC_StateDAL dalLOC_StateDAL=new LOC_StateDAL();

            if (dalLOC_StateDAL.SaveState(model))
            {
                return RedirectToAction("LOC_StateList");
            }
            
            return View();
        }
        #endregion

        #region Delete
        public IActionResult Delete(int ? StateID) {
            dalLOC_StateDAL.PR_LOC_deleteCity_FollowedBy_States(StateID);
            dalLOC_StateDAL.PR_LOC_State_Delete(StateID);
            return RedirectToAction("LOC_StateList");
        }
        #endregion

        #region SearchState
        public IActionResult SearchState(string StateName)
        {
            DataTable dt = dalLOC_StateDAL.PR_State_SelectByStateName(StateName);
            return View("LOC_StateList", dt);
        }
        #endregion
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminPanel_New</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminPanel_New.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LOCATION</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Country" asp-controller="LOC_Country" asp-action="LOC_CountryList">Country</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="States" asp-controller="LOC_State" asp-action="LOC_StateList">State</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="City" asp-controller="LOC_City" asp-action="LOC_CityList">City</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Student" asp-controller="MST_Student" asp-action="MST_StudentList">Student</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Branch" asp-controller="MST_Branch" asp-action="MST_BranchList">Branch</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>